"""Store money as numeric and Wise ids as bigint

Existing amounts are rounded to 2 decimals. Amounts that NUMERIC(10,2)
cannot hold (1e8 or more, infinite, NaN) stop the upgrade with a list of
the affected rows, so they can be corrected first.

Downgrading fails once a Wise transfer id no longer fits in INTEGER.

Revision ID: 84c70b91eeac
Revises: 503a98bf8050
Create Date: 2026-09-26 15:51:54.494794

"""

from alembic import context, op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "84c70b91eeac"
down_revision = "503a98bf8050"
branch_labels = None
depends_on = None


def check_amounts() -> None:
    if context.is_offline_mode():
        return
    bad = []
    for table in ("complaints", "transactions"):
        # PostgreSQL sorts NaN above every number, so this also catches NaN
        rows = op.get_bind().execute(
            sa.text(
                f"SELECT id, amount FROM {table} "
                "WHERE NOT (amount > -99999999.995 AND amount < 99999999.995)"
            )
        )
        bad += [f"{table} id={row.id} amount={row.amount}" for row in rows]
    if bad:
        raise RuntimeError(
            "These amounts do not fit NUMERIC(10,2); correct them and run the "
            "upgrade again: " + "; ".join(bad)
        )


def upgrade() -> None:
    check_amounts()
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "complaints",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "transfer_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "transactions",
        "transfer_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "complaints",
        "amount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
