"""Add transaction model

Revision ID: 925eeabcaa89
Revises: e6ad52666360
Create Date: 2022-06-03 18:14:09.089657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "925eeabcaa89"
down_revision = "e6ad52666360"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.String(length=120), nullable=False),
        sa.Column("transfer_id", sa.Integer(), nullable=False),
        sa.Column("target_account_id", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("complaint_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
